###

POST http://localhost:3999/register
Content-Type: application/json 

{
  "username": "sagar",
  "name": "Sagar Babu",
  "password": "sagar@babu",
  "gender": "Male",
  "location": "Khammam"
}

###
GET http://localhost:3004/

###
POST http://localhost:3999/login/
Content-Type: application/json

{ "username": "sagar",
  "password": "sagar@babu"  
}

###
POST http://localhost:3004/register
Content-Type: application/json 

{
  "username": "saara",
  "password": "123Kadafd"
}
