###

POST http://localhost:3999/register
Content-Type: application/json 

{
  "gmail": "s@gmail.com",
  "name": "Sagar Babu",
  "password": "sagar@babu"
}

###
GET http://localhost:3999/users

###
POST http://localhost:3999/login/
Content-Type: application/json

{ "gmail": "s@gmail.com",
  "password": "sagar@babu"  
}

###
POST http://localhost:3004/register
Content-Type: application/json 

{
  "username": "saara",
  "password": "123Kadafd"
}
